packages:
  - "app"
  - "server"
  - "app-server-shared"
  - "deps/access-token-jwt"
  - "deps/counter"
  - "deps/oauth2-bearer"
  - "deps/utils"
  - "deps/model/ts/packages/model"
  - "deps/model/ts/packages/value"
  - "deps/model/ts/packages/util"
  - "deps/model/ts/packages/zone"
